### ISSUE TITLE
I got a uint8arrays error when building the application which is Uint8Arrays not found in the cacho package 

### ISSUE THREAD

**Issue by jingledongding** [ceramicnetwork/js-did#141]
# Description

error: Error: While trying to resolve module `uint8arrays` from file `/Users/admin/User/workspace/private/GoodMorning/node_modules/@didtools/cacao/dist/siwx/siwTezos.js`, the package `/Users/admin/User/workspace/private/GoodMorning/node_modules/@didtools/cacao/node_modules/uint8arrays/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/Users/admin/User/workspace/private/GoodMorning/node_modules/@didtools/cacao/node_modules/uint8arrays/index`. Indeed, none of these files exist:

  * /Users/admin/User/workspace/private/GoodMorning/node_modules/@didtools/cacao/node_modules/uint8arrays/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * /Users/admin/User/workspace/private/GoodMorning/node_modules/@didtools/cacao/node_modules/uint8arrays/index/index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
    at DependencyGraph.resolveDependency (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/node-haste/DependencyGraph.js:272:17)
    at Object.resolve (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/lib/transformHelpers.js:177:21)
    at Graph._resolveDependencies (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/DeltaBundler/Graph.js:432:35)
    at Graph._processModule (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/DeltaBundler/Graph.js:218:38)
    at async Graph._addDependency (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 3)
    at async Graph._processModule (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/DeltaBundler/Graph.js:263:5)
    at async Graph._addDependency (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/DeltaBundler/Graph.js:314:20)
    at async Promise.all (index 2)
    at async Graph._processModule (/Users/admin/User/workspace/private/GoodMorning/node_modules/metro/src/DeltaBundler/Graph.js:263:5)

# Technical Information

My env: {
  MacOs: 13.1
  React-native: 0.71
  metro: 0.72

**Comment by jingledongding** [comment]
some one can help ?

**Comment by stbrody** [comment]
@zachferland could you take a look at this?

**Comment by zachferland** [comment]
hey, could you try the following - https://forum.ceramic.network/t/failed-to-resolve-uint8arrays/704/10?u=zfer

**Comment by jingledongding** [comment]
ooh! I got it, Thanks you
