### ISSUE TITLE
Unsafe-eval caused by rpc-utils

### ISSUE THREAD

**Issue by lsmod** [ceramicnetwork/js-did#78]
# Description

While developing a web extension, I ran into an security error (see bellow). Its thrown at me by browsers (FF & chrome).

Following the trace I can see `dids` package requiring `rpc-utils`  is causing it.
There is a work around adding security directive in web extension manifest file. 
BUT! It's only allow in deprecated manifest file

# Technical Information

`
Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' blob: filesystem:".

    at Function (<anonymous>)
    at rpc-utils.esm.js:887:1
    at createCommonjsModule (rpc-utils.esm.js:138:33)
    at Module../node_modules/rpc-utils/dist/rpc-utils.esm.js (rpc-utils.esm.js:141:1)
    at __webpack_require__ (bootstrap:19:1)
    at Object../node_modules/dids/lib/did.js (did.js:16:21)
    at __webpack_require__ (bootstrap:19:1)
    at Object../node_modules/dids/lib/index.js (index.js:14:14)
    at __webpack_require__ (bootstrap:19:1)
    at Object../src/popup/Popup.tsx (Popup.tsx:2:1)
`

**Comment by lsmod** [comment]
Solved by bumping `dids` package to version 3.1.0
